# image with Node, Elm and Nginx
FROM debian:latest
ENV DEBIAN_FRONTEND=noninteractive
EXPOSE 8000 80
# prepare
RUN echo "force-unsafe-io" > /etc/dpkg/dpkg.cfg.d/02apt-speedup && \
    echo "Acquire::http {No-Cache=True;};" > /etc/apt/apt.conf.d/no-cache &&\
    apt-get update && \
    apt-get -y install apt-utils curl gnupg nginx

RUN curl -sL https://deb.nodesource.com/setup_8.x | bash - && \
    apt-get install -y nodejs && \
    npm install -g elm && \
    npm install -g elm-test