# image with Node, Elm and Nginx
FROM debian:latest

# prepare
RUN apt-get -y update
RUN apt-get -y install apt-utils

RUN apt-get -y install curl

RUN apt-get -y install gnupg
RUN apt-get -y install sudo

RUN curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
RUN apt-get install -y nodejs

RUN sudo npm install -g elm
RUN sudo npm install -g elm-test

RUN apt-get install -y nginx

EXPOSE 8000 80
